### ISSUE TITLE
CPU frequency unit on Web interface is wrong

### ISSUE THREAD

**Issue by polyrumors** [sunfounder/pironman5#3]
The CPU frequency number seems to be MHz, but the unit keeps showing GHz.

<img width="1035" alt="Screenshot 2024-06-20 at 5 31 58 PM" src="https://github.com/sunfounder/pironman5/assets/48437891/8fad75f2-36e9-4a02-8e4b-499e8c3eb4cb">

**Comment by deependdesigns** [comment]
Search the /opt/pironman5 for "GHz" and you will find a .js file.  This is where the string "GHz" is defined.  Just change it to "MHz" and it will be correct.

**Comment by cavonlee** [comment]
@polyrumors @deependdesigns Thank you, will fix it on the next update
